tweetme/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home, name='home'),
    url(r'^tweet/',include('tweets.urls', namespace='tweet')),
    url(r'^api/tweet/',include('tweets.api.urls', namespace='tweet-api')),
]

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tweets/api/urls.py
from django.conf.urls import url

from .views import (
                    TweetListAPIView
                    )

urlpatterns = [
    url(r'^$',TweetListAPIView.as_view(), name='list'), # /api/tweet/

    # url(r'^create/$',TweetCreateView.as_view(), name='create'), # /tweet/create/

    # url(r'^(?P<pk>\d+)/$',TweetDetailView.as_view(), name='retrieve'), # /tweet/1/

    # url(r'^(?P<pk>\d+)/update/$',TweetUpdateView.as_view(), name='update'), # /tweet/1/update/

    # url(r'^(?P<pk>\d+)/delete/$',TweetDeleteView.as_view(), name='delete'), # /tweet/1/delete/
]

tweets/urls.py
from django.conf.urls import url

from .views import (
                    TweetDetailView,
                    TweetListView,
                    TweetCreateView,
                    TweetUpdateView,
                    TweetDeleteView
                    )

urlpatterns = [
    url(r'^$',TweetListView.as_view(), name='list'), # /tweet/

    url(r'^create/$',TweetCreateView.as_view(), name='create'), # /tweet/create/

    url(r'^(?P<pk>\d+)/$',TweetDetailView.as_view(), name='retrieve'), # /tweet/1/

    url(r'^(?P<pk>\d+)/update/$',TweetUpdateView.as_view(), name='update'), # /tweet/1/update/

    url(r'^(?P<pk>\d+)/delete/$',TweetDeleteView.as_view(), name='delete'), # /tweet/1/delete/
]

accounts/models.py
from django.db import models

# Create your models here.

tweets/models.py
from django.db import models
# from django.core.exceptions import ValidationError
from django.conf import settings
from django.urls import reverse
from .validators import validate_content


# Create your models here.
class Tweet(models.Model):
    user        = models.ForeignKey(settings.AUTH_USER_MODEL)
    content     = models.CharField(max_length=140, validators = [               validate_content])
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return str(self.content)

    def get_absolute_url(self):
        return reverse("tweet:retrieve", kwargs={"pk":self.pk})

    # def clean(self, *args, **kwargs):
    #     content = self.content

    #     if content == "abc":
    #         raise ValidationError("Content cannot be abc")

    #     return super(Tweet, self).clean(*args, **kwargs)

tweets/forms.py
from django import forms

from .models import Tweet

class TweetModelForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = [
            # "user",
            "content"
        ]

    # def clean_content(self, *args, **kwargs):
    #     content = self.cleaned_data.get("content")
    #     if content == "abc":
    #         raise forms.ValidationError("Cannot be ABC")

    #     return content

accounts/views.py
from django.shortcuts import render

# Create your views here.

tweetme/views.py
from django.shortcuts import render

def home (request):
    return render(request, "home.html", {})

tweets/api/views.py
from rest_framework import generics
from rest_framework.permissions import IsAdminUser

from .serializers import TweetModelSerializer
from tweets.models import Tweet

class TweetListAPIView(generics.ListAPIView):
    serializer_class = TweetModelSerializer

    def get_queryset(self):
        return Tweet.objects.all()

tweets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (
                                  DetailView,
                                  ListView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView
                                  )

from .forms import TweetModelForm
from .mixins import FormUserNeededMixin, UserOwnerMixin
from .models import Tweet


# Create #########################

class TweetCreateView(LoginRequiredMixin, FormUserNeededMixin, CreateView):
    form_class = TweetModelForm
    template_name = 'tweets/create_view.html'
    #success_url = reverse_lazy("tweet:detail")
    login_url = "/admin/"

    # def form_valid(self, form):
    #     if self.request.user.is_authenticated():
    #         form.instance.user = self.request.user
    #         return super(TweetCreateView, self).form_valid(form)
    #     else:
    #         form._errors[forms.forms.NON_FIELD_ERRORS] = ErrorList(["User must be logged in to continue"])
    #         return self.form_invalid(form)


# Retrieve #########################

class TweetDetailView(DetailView):
    template_name = "tweets/detail_view.html"
    queryset =Tweet.objects.all()

class TweetListView(ListView):

    template_name = "tweets/list_view.html"

    def get_queryset(self, *args, **kwargs):
        qs = Tweet.objects.all()
        query = self.request.GET.get("q", None)

        if query is not None:
            qs = qs.filter(
                           Q(content__icontains=query) |
                           Q(user__username__icontains=query)
                           )

        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(TweetListView, self).get_context_data(*args, **kwargs)
        # print(context)
        return context

# Update #########################

class TweetUpdateView(LoginRequiredMixin, UserOwnerMixin, UpdateView):
    queryset =Tweet.objects.all()
    form_class = TweetModelForm
    #success_url = reverse_lazy("tweet:list")
    template_name = 'tweets/update_view.html'

# Delete #########################

class TweetDeleteView(LoginRequiredMixin, DeleteView):
    model =Tweet
    success_url = reverse_lazy("tweet:list")
    template_name = 'tweets/delete_view.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Tweetme test{% endblock title %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class='container'>
      {% block content %}
      {% endblock content %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% block script %}{% endblock script %}
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}{{block.super}} | Welcome{%endblock title%}

{% block content %} <h1>Tweet </h1>{%endblock content%}

tweets/templates/tweets/create_view.html
{% extends "base.html" %}

{% block title %}{{block.super}} | Create Tweet{%endblock title%}

{% block content %}
  {% include "tweets/form.html" with form=form btn_title='Tweet'%}
{% endblock content %}

tweets/templates/tweets/delete_view.html
{% extends "base.html" %}

{% block title %}{{block.super}} | Are you sure you want to delete "{{object}}"? {%endblock title%}

{% block content %}
  <form action ="" method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"?</p>
    <input type="submit" value="Confirm" />
  </form>
{% endblock content %}

tweets/templates/tweets/detail_view.html
{% extends "base.html" %}

{% block title %}{{block.super}} | Detail {{object}} {%endblock title%}

{% block content %}
  {{object.content}}</br>
  {{object.user}}</br>
  {{object.timestamp | timesince}}</br>
{% endblock content %}

tweets/templates/tweets/form.html
{% load crispy_forms_tags %}
<form class='form' method='POST' action =''>
  {% csrf_token %}
  {{form | crispy}}
  <input type="submit" value="{{btn_title}}">
</form>

tweets/templates/tweets/list_view.html
{% extends "base.html" %}

{% block title %}{{block.super}} | List{%endblock title%}

{% block script %}
<script>
  $(document).ready(function() {
    console.log("working")

    $.ajax({
        url: "{% url 'tweet-api:list' %}",
        method: "GET",
        success: function(data) {
          // console.log(data)
          $.each(data, function(key, value) {
            // console.log(key)
            // console.log(value)
            var tweetKey = key;
            var tweetContent = value.content;
            var tweetUser = value.user;

            $("#tweet-container").append(
              "<div class=\"media\"><div class=\"media-body\">"+tweetContent+"</br> via "+tweetUser.username+"</div></div><hr />"
              )
          })
        },
        error: function(data) {
          console.log("Error")
          console.log(data)
        },
    });


  });
</script>
{% endblock script %}

{% block content %}

  {% include "tweets/search_form.html" %} <br/>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
    <div id='tweet-container'>

    </div>
      {% for object in object_list%}
        <div class="media">
          <div class="media-left">
            <a href="#">
              {% if object.image %}
              <img class="media-object" src="..." alt="...">
              {% endif %}
            </a>
          </div>
           <div class="media-body">
            {{object.content}}</br>
            via {{object.user}} | {{object.timestamp | timesince}} ago | <a href='{{object.get_absolute_url}}'>View</a>
          </div>
        </div>
        <hr />
        {% empty %}
          {% if request.GET.q %}
            <p>No tweets found.</p>
          {% else %}
            <p>No tweets yet.</p>
          {% endif %}
      {% endfor %}
    </div>
  </div>
{% endblock content %}

tweets/templates/tweets/search_form.html
<div class="row">
  <div class="col-sm-12 text-center">
    <form method='GET' action='{% url "tweet:list" %}' class="form-inline">
      <div class="form-group">
        {# <label for="q">Search</label> #}
        <input type = 'text' class="form-control" name='q' placeholder='Your search' value='{{request.GET.q}}'/>
      </div>
      <input type = 'submit' class="btn btn-default" value='Search' />
    </form>
  </div>
</div>

tweets/templates/tweets/update_view.html
{% extends "base.html" %}

{% block title %}{{block.super}} | Update "{{object}}"? {%endblock title%}

{% block content %}
  {% include "tweets/form.html" with form=form btn_title='Update Tweet'%}
{% endblock content %}